ARG NETWORK_EE_IMAGE=quay.io/ansible/network-ee:latest

FROM $NETWORK_EE_IMAGE as requirements
# =============================================================================

WORKDIR /usr/local/lib/python3.8/site-packages/ansible_test/_data/requirements
RUN mkdir -p /tmp/src \
  && cp constraints.txt /tmp/src/upper-constraints.txt \
  && cat units.txt | sort -u > /tmp/src/requirements.txt

RUN if [ -f sanity.txt ] ; then \
      echo "Installing sanity.txt requirements" ; \
      cat sanity.txt | sort -u >> /tmp/src/requirements.txt ; \
      sed -i 's/rstcheck/rstcheck==3.1.1/' /tmp/src/requirements.txt ; \
    else \
      echo "Installing sanity.*.txt requirements" ; \
      cat sanity.*.txt | sort -u >> /tmp/src/requirements.txt ; \
    fi
FROM quay.io/ansible/python-builder:latest as builder
# =============================================================================

ARG ZUUL_SIBLINGS=""
COPY --from=requirements /tmp/src /tmp/src
COPY . /tmp/src
RUN cat /tmp/src/test-requirements.txt | sort -u >> /tmp/src/requirements.txt
RUN assemble

FROM $NETWORK_EE_IMAGE
# =============================================================================

COPY --from=builder /output/ /output/
RUN /output/install-from-bindep \
  && rm -rf /output/
