---
- project:
    templates:
      - network-ee-container-image-jobs
    check:
      jobs: &jobs
        - network-ee-tox-ansible-builder
    gate:
      jobs: *jobs
    post:
      jobs:
        - network-ee-upload-container-image:
            vars:
              upload_container_image_promote: false
        - network-ee-upload-container-image-stable-2.9:
            vars:
              upload_container_image_promote: false
    periodic:
      jobs:
        - network-ee-upload-container-image:
            vars:
              upload_container_image_promote: false
        - network-ee-upload-container-image-stable-2.9:
            vars:
              upload_container_image_promote: false
